### CON WEDU NO SE PUEDE HACER | USAR OTRA RED O USAR DATOS y añadir esta ip al mongo atlas: 0.0.0.0 que permite entrar a todo el mundo MENOS A LA RED WEDU POR SER UNA RED DE INSTITUCIÓN PÚBLICA, lo ideal es poner tu ip PÚBLICA ACTUAL, si no sabes cual es tu ip pública puedes buscar en google "¿Cuál es mi ip publica?" y te lo dice en cualquier enlace que te aparece y listo o si no a la hora de acceder al "IP ACCES LIST" aparece un botón que dice "ADD CURRENT IP ADDRESS" y le das click y listo.
POST http://localhost:5000/todo HTTP/1.1
Content-Type: application/json

{
    "title": "Aprendiendo MongoDB",
    "description": "Práctica de Python en MongoDB"
}

###
GET http://localhost:5000/todo HTTP/1.1

###
GET http://localhost:5000/todo/69e9cfd797b33d38610e6f44 HTTP/1.1

###
PUT http://localhost:5000/todo/69e9d4eebe67cf5e773b35ce HTTP/1.1
Content-Type: application/json

{
    "title": "Learn Python and Flask",
    "done": true
}

###
DELETE http://localhost:5000/todo/69e9d4eebe67cf5e773b35ce HTTP/1.1